### ISSUE TITLE
Siri support

### ISSUE THREAD

**Issue by kekko7072** [mralexhay/Booky#6]
Hey is SIRI supported? 
From WWDC22 session seems yes but I am not able to make it run, it always search on web.
Thanks nice job.

**Comment by boxabirds** [comment]
Booky as it is doesn't automatically add shortcuts. You still have to manually add the shortcut. 

Stay tuned for a small increment that automatically adds the intents…

**Comment by kekko7072** [comment]
Ok thank i successfully added on shortcut app. On the other hand I am facing some issue on open and add but think I will check the code fist. Closing for now

**Comment by boxabirds** [comment]
Apologies I've not released my changes to this as I've had such bad luck getting consistent responses from Siri that I've paused investment in this area for the time being. The great news is that it's really only a few lines of code -- accepting that that code probably won't work a lot of the time due to bugs in how Siri seems to recognise phrases.
